name: Create Release with Nix Portable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27

      - name: Bundle the application
        run: |
          nix bundle --bundler github:DavHau/nix-portable -o nixvim-stable-bundle \
            .#stable --accept-flake-config
          nix bundle --bundler github:DavHau/nix-portable -o nixvim-nightly-bundle \
            .#nightly --accept-flake-config

      - name: Compress the bundle
        run: |
          tar -czvf nixvim-stable.tar.gz nixvim-stable-bundle/bin/nvim
          tar -czvf nixvim-nightly.tar.gz nixvim-nightly-bundle/bin/nvim

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nixvim-stable.tar.gz
            nixvim-nightly.tar.gz
